2025-03-31 03:23:32,130 - ERROR - Failed to connect to server
2025-03-31 03:25:05,646 - ERROR - Failed to connect to server
2025-03-31 03:26:19,634 - ERROR - Failed to connect to server: HTTPConnectionPool(host='localhost', port=5051): Max retries exceeded with url: /api/test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000011CD953FCB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-03-31 03:43:18,200 - DEBUG - Starting new HTTP connection (1): 192.168.2.6:5051
2025-03-31 03:43:18,218 - DEBUG - http://192.168.2.6:5051 "GET /api/test HTTP/1.1" 200 80
